# Generated by Django 4.0.3 on 2024-04-17 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealer_portal', '0002_cardealer_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicles',
            name='hiring_amount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
