# Generated by Django 4.0.3 on 2024-04-17 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealer_portal', '0003_vehicles_hiring_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicles',
            old_name='car_name',
            new_name='name',
        ),
    ]
