# Generated by Django 4.0.3 on 2024-04-17 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealer_portal', '0005_rename_name_vehicles_car_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='hiring_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
